### ISSUE TITLE
[feature request] numtype, prectype and related conversions

### ISSUE THREAD

**Issue by putianyi889** [emmt/TypeUtils.jl#2]
numtype for Number type, prectype for precision type.

Examples:
```julia
numtype(Matrix{Vector{Complex{Float64}}) = Complex{Float64}
numtype(Set{BitArray}) = Bool

prectype(Complex{Float16}) = Float16
prectype(Array{Complex{Rational{BigInt}}}) = BigInt
```

**Comment by putianyi889** [comment]
Just found Unitless.jl which this request might belong to... what a confusing name that is

**Comment by emmt** [comment]
Some day I will merge `Unitless` and `TypeUtils` in a single package.

**Comment by emmt** [comment]
Done as of [`TypeUtils`](https://github.com/emmt/TypeUtils.jl) version 1.0.0: you no longer need [`Unitless`](https://github.com/emmt/Unitless.jl) which only remains for backward compatibility (importing all its methods from `TypeUtils`).
